Update main.c
Missing header and for me did work with out adding it main.c: In function 'main':
main.c:22:5: warning: implicit declaration of function 'snd_init' [-Wimplicit-function-declaration]
main.c:100:5: warning: implicit declaration of function 'snd_shutdown' [-Wimplicit-function-declaration]
I hate warnings of any kind :)